# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
