# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0003_auto_20171013_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
