# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orthomodoweb', '0007_collectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthoModoJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('scan_date_when_added', models.DateTimeField(blank=True, null=True)),
                ('orthotrac_reference_no', models.CharField(max_length=100)),
                ('orthotrac_analysis_done', models.BooleanField(default=None)),
                ('orthotrac_analysis_notes', models.TextField(blank=True)),
                ('is_stl_file_prepared', models.BooleanField(default=None)),
                ('stl_marked_as_prepared_when', models.DateTimeField(blank=True, null=True)),
                ('is_printed', models.BooleanField(default=None)),
                ('is_printed_marked_when', models.DateTimeField(blank=True, null=True)),
                ('orthomodel_notes', models.TextField(blank=True)),
                ('planned_collection_date', models.DateField(blank=True, null=True)),
                ('planned_collection_time', models.TimeField(blank=True, null=True)),
                ('collection_notes', models.TextField(blank=True)),
                ('is_collected', models.BooleanField(default=None)),
                ('is_collected_marked_when', models.DateTimeField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=None)),
                ('flag_status_set_when', models.DateTimeField(blank=True, null=True)),
                ('flag_status_note', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.Clinician')),
                ('collection_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.CollectionType')),
                ('flag_status_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_flag_status_set_by', to=settings.AUTH_USER_MODEL)),
                ('is_collected_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_is_collected_marked_by', to=settings.AUTH_USER_MODEL)),
                ('is_printed_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_is_printed_marked_by', to=settings.AUTH_USER_MODEL)),
                ('orthomodel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.OrthoModelType')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.Patient')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.Printer')),
                ('scan_date_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_scan_date_entered_by', to=settings.AUTH_USER_MODEL)),
                ('stl_marked_as_prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_stl_marked_as_prepared_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
