# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0008_orthomodojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthomodojob',
            name='print_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
