# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0009_orthomodojob_print_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthomodojob',
            name='orthotrac_reference_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
