# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0010_auto_20171019_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orthomodojob',
            old_name='scan_date_when_added',
            new_name='scan_date_entered_when',
        ),
    ]
