# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orthomodoweb', '0011_auto_20171024_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthomodojob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orthomodojob',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthomodojob_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
