# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0012_auto_20171024_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='orthomodojob',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.ModelType'),
            preserve_default=False,
        ),
    ]
