# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0013_auto_20171108_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthomodojob',
            name='model_type',
        ),
    ]
