# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0014_remove_orthomodojob_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthomodojob',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.ModelType'),
            preserve_default=False,
        ),
    ]
