# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0015_orthomodojob_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthomodojob',
            name='orthotrac_reference_no',
        ),
    ]
