# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0017_auto_20171109_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthomodojob',
            name='is_poured',
        ),
        migrations.RemoveField(
            model_name='orthomodojob',
            name='is_poured_marked_by',
        ),
        migrations.RemoveField(
            model_name='orthomodojob',
            name='is_poured_marked_when',
        ),
        migrations.RemoveField(
            model_name='orthomodojob',
            name='poured_date',
        ),
    ]
