# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orthomodoweb', '0019_auto_20171109_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_made', models.BooleanField(default=False)),
                ('made_date', models.DateTimeField(blank=True, null=True)),
                ('is_made_marked_when', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('is_made_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_item_is_made_marked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.RenameModel(
            old_name='OrthoModelType',
            new_name='LabItemMaterial',
        ),
        migrations.RemoveField(
            model_name='orthomodojob',
            name='orthomodel_notes',
        ),
        migrations.RemoveField(
            model_name='orthomodojob',
            name='orthomodel_type',
        ),
        migrations.AddField(
            model_name='lab_item',
            name='lab_item_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.LabItemMaterial'),
        ),
        migrations.AddField(
            model_name='lab_item',
            name='lab_item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.LabItemType'),
        ),
        migrations.AddField(
            model_name='lab_item',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_item_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab_item',
            name='orthomodojob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.OrthoModoJob'),
        ),
    ]
