# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0020_auto_20171109_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lab_item',
            new_name='LabItem',
        ),
    ]
