# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0021_auto_20171109_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedModelUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='orthomodojob',
            name='created_model_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orthomodoweb.CreatedModelUse'),
        ),
    ]
