# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthomodoweb', '0022_auto_20171113_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdmodeluse',
            name='code',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createdmodeluse',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
